# Source: valheim-k8s/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim-server
spec:
  selector:
    matchLabels:
      app: valheim-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: valheim-server
    spec:
      containers:
      - image: "lloesche/valheim-server:latest"
        name: valheim-server
        env:
        - name: SERVER_NAME
          value: kuberheim
        - name: WORLD_NAME
          value: kuberheim-world
        - name: SERVER_PASS
          value: hpchpc
        - name: SERVER_PORT
          value: "2456"
        ports:
        - containerPort: 2456
          name: gameport
        - containerPort: 2457
          name: queryport
        volumeMounts:
        - name: valheim-data
          mountPath: /config
        
        resources:
          {}
      - name: playit
        image: ghcr.io/playit-cloud/playit-agent:0.15
        env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: playit-gg-secret
                  key: SECRET_KEY
      volumes:
      - name: valheim-data
        persistentVolumeClaim:
          claimName: valheim-claim            
