apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server:latest  # Or specific version if needed
          env:
            - name: EULA
              value: "TRUE"
            - name: MODE
              value: "survival"
            - name: INIT_MEMORY
              value: 8G
            - name: MAX_MEMORY
              value: 12G
          resources:
            requests:
              cpu: 2  # Adjust based on expected workload
              memory: "12Gi"  # Adjust based on expected workload
            limits:
              cpu: 3  # Adjust based on expected workload
              memory: "14Gi"  # Adjust based on expected workload
          volumeMounts:
          - name: minecraft-data
            mountPath: /data
        - name: playit
          image: ghcr.io/playit-cloud/playit-agent:0.15
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: playit-gg-secret
                  key: SECRET_KEY
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-claim
