apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-storage
