apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-pv-claim
  labels:
    app: syncthing
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
