apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-pvc-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
