apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-pv-data
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.0.20
    path: /volume2/cluster-storage/syncthing/data
  mountOptions:
    - nfsvers=4.1
