apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-pv-data-nfs
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.0.20
    path: /volume2/cluster-storage/syncthing/data
  mountOptions:
    - nfsvers=4.1    
    - rsize=1048576
    - wsize=1048576
    - tcp
    - hard
    - noatime
    - nconnect=4
