apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server:latest  # Or specific version if needed
          env:
            - name: EULA
              value: "TRUE"
            - name: MODE
              value: "survival"
            - name: INIT_MEMORY
              value: 4G
            - name: MAX_MEMORY
              value: 8G
          resources:
            {}
          volumeMounts:
          - name: minecraft-data
            mountPath: /data
        - name: playit
          image: ghcr.io/playit-cloud/playit-agent:0.15
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: playit-gg-secret
                  key: SECRET_KEY
      nodeName: node-01
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-claim
